### PR TITLE
Add elevation processing for GPX files

### PR DESCRIPTION
**Pull request by ray66**
This PR adds support for elevation data in GPX files. There is a slight drawback for tracks without any elevation data. In this case a diagram with a straight line at 'null' is drawn. It would be better to just display a text like "no elevation data" instead.

### CODE REVIEW

**Comment by martin-ueding** [comment]
Thank you for this contribution!

When there is no altitude data, the corresponding time series data frame should just not have the `"altitude"` column. So we should add some more logic that checks whether we really want to have this column. We could use `Series.any` to check whether there are any non-zero and non-nan (None) elements in there:

```python
df = pd.DataFrame(points, columns=["time", "latitude", "longitude", "altitude"])
if not df["altitude"].any():
    del df["altitude"]
return df
```

Do you want to make this change or shall I do that? I'm happy to do it, but I don't want to take it away from you 😊

**Comment by ray66** [comment]
Thanks for your answer. I prefer that you make the change.

**Comment by martin-ueding** [comment]
I've merged your changes and put mine on top. It will be available in version 0.20.0.

**Comment by martin-ueding** [comment]
Version 0.20.0 is released you can update and try it out. If the issue persists, please reopen this ticket.

**Pull request merged**
